# Generated by Django 5.2.9 on 2025-12-02 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('designation', models.CharField(choices=[('developer', 'Developer'), ('manager', 'Manager'), ('designer', 'Designer')], max_length=50)),
                ('department', models.CharField(choices=[('it', 'IT'), ('hr', 'HR Department'), ('sales', 'Sales')], max_length=50)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('joined_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
